spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  r2dbc:
    url: r2dbc:pool:mysql://20.11.22.159:3306/practice
    username: root
    password: root
  application:
    name: COUNTRY
  config:
    import: configserver:http://localhost:8086
  webflux:
    base-path: /country
server:
  servlet:
    context-path-state: /state/
  port: 8090






